version: '3.8'

networks:
  app-network:


volumes:
  db-postgres:


services:

  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:


  postgres:
    image: postgres:12.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - db-postgres:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      app-network:


  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:
